### ISSUE TITLE
pip install xstac breaks gcsfs (due to pip install adlfs)

### ISSUE THREAD

**Issue by cisaacstern** [TomAugspurger/xstac#17]
Encountered this issue while using xstac for https://github.com/pangeo-forge/pangeo-forge-orchestrator/pull/1

Reproducer:

1. Create and activate a new conda env (python=3.8)
2. `conda install gcsfs`
3. Open an interpreter: `import gcsfs`works
4. `pip install git+https://github.com/TomAugspurger/xstac.git`
5. Open an interpreter: `import gcsfs` fails with:
```
>>> import gcsfs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cs/.pyenv/versions/anaconda3-2019.10/envs/pfo2/lib/python3.8/site-packages/gcsfs/__init__.py", line 5, in <module>
    from .core import GCSFileSystem
  File "/Users/cs/.pyenv/versions/anaconda3-2019.10/envs/pfo2/lib/python3.8/site-packages/gcsfs/core.py", line 1095, in <module>
    class GCSFile(fsspec.spec.AbstractBufferedFile):
AttributeError: 'EntryPoint' object has no attribute 'AbstractBufferedFile'
```
My workaround is to install xstac from [a branch which drops the adlfs dependency in pyproject.toml](https://github.com/cisaacstern/xstac/compare/main..drop-adlfs-dep); this appears to work. Presumably the `pip install adlfs` triggered by the git install of xstac is not resolving correctly.

Perhaps the solution is to make a conda-forge recipe for xstac?

**Comment by TomAugspurger** [comment]
Fixed in https://github.com/TomAugspurger/xstac/pull/18, by removing adlfs as a required dependency.

**Comment by cisaacstern** [comment]
Belated thanks for this prompt fix, Tom!
